import React from 'react';
import { render } from '@testing-library/react';
import { Admin } from "../index";

describe('Admin component', () => {
  test('renders dashboard text', () => {
    const { getByText } = render(<Admin />);
    const dashboardText = getByText(/Dashboard/i);
    expect(dashboardText).toBeInTheDocument();
  });

  test('renders sidebar component', () => {
    const { getByTestId } = render(<Admin />);
    const sidebarComponent = getByTestId('sidebar');
    expect(sidebarComponent).toBeInTheDocument();
  });

  test('renders title and meta tag', () => {
    const { getByText, getByTestId } = render(<Admin />);
    const titleElement = getByText(/Dashboard/i);
    expect(titleElement).toBeInTheDocument();

    const metaTag = getByTestId('meta-description');
    expect(metaTag).toHaveAttribute('content', 'Generated by create-next-app');
  });

  test('renders favicon', () => {
    const { getByTestId } = render(<Admin />);
    const favicon = getByTestId('favicon');
    expect(favicon).toHaveAttribute('href', '/gsi-logo.png');
  });
});
