import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import router, { useRouter } from "next/router";
import { useEffect } from "react";
import { Sidebar } from "~/components/Sidebar";
import { api } from "~/utils/api";

const AdminBlog = () => {
  const { user, isLoaded } = useUser();
  const user_role = user?.publicMetadata.admin;

  useEffect(() => {
    if (isLoaded && user_role !== 'admin') {
      router.push('/home');
    }
  }, [isLoaded, user_role]);

  if (!isLoaded) {
    return <div>Loading...</div>;
  }
  if (isLoaded && user_role !== 'admin'){
    return <div>UNAUTHORIZED</div>;
  }
  return (
    <>
      <Head>
        <title>Blogs | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <div className="flex">
        <Sidebar />

        <div className="mx-auto mt-72 text-5xl"> Blogs </div>
      </div>
    </>
  );
};

export default AdminBlog;
