import Head from "next/head";

import { Footer } from "~/components/Footer";
import { LoginForm } from "./LoginForm";

const Register = () => {
  return (
    <>
      <Head>
        <title> Register </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.jpeg" />
      </Head>

      <LoginForm />
      <Footer />
    </>
  );
};

export default Register;
