import Head from "next/head";

import { Footer } from "~/components/Footer";
import RegisterForm from "./RegisterForm";

const Register = () => {
  return (
    <>
      <Head>
        <title> Register </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <RegisterForm />
      <Footer />
    </>
  );
};

export default Register;
