import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Loading from "~/components/Loading";
import { Sidebar } from "~/components/Sidebar";
import Unauthorized from "~/components/Unauthorized";
import EditorOutput from "~/components/editor/EditorOutput";
import { api } from "~/utils/api";

const BlogDetailsPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [blogData, setblogData] = useState<any>(null);
  const [editorBlocks, setEditorBlocks] = useState([]);
  const [initialEditorData, setinitialEditorData] = useState();
  const getBlog = api.blog.getById.useQuery({ id: id as string });

  useEffect(() => {
    if (getBlog.data && !blogData && getBlog.data !== blogData) {
      setblogData(getBlog.data);
      const initialEditorData = JSON.parse(getBlog.data.content);
      setinitialEditorData(initialEditorData);
      setEditorBlocks(initialEditorData.blocks);
    }
  }, [getBlog.data, blogData]);

  const { user, isLoaded } = useUser();
  const user_role = user?.publicMetadata.admin;

  useEffect(() => {}, [isLoaded, user_role]);
  if (!isLoaded) {
    return <Loading />;
  }
  if (user_role !== "admin") {
    return <Unauthorized />;
  }

  return (
    <div className="flex">
      <Head>
        <title> Blog | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <Sidebar />

      {blogData && (
        <div className="mx-auto mb-12 mt-8 max-w-[1200px]">
          <EditorOutput content={initialEditorData} />
        </div>
      )}
    </div>
  );
};

export default BlogDetailsPage;
