import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { Sidebar } from "~/components/Sidebar";
import { GrFormNextLink, GrFormPreviousLink } from "react-icons/gr";
import { commentData } from "~/data/commentData";
import FilterByProjectName from "~/components/FilterByProjectName";
import SearchByName from "~/components/SearchByName";
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import {
  AiOutlineSortAscending,
  AiOutlineSortDescending,
} from "react-icons/ai";

const Comments = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage] = useState(5);
  const [tableData, setTableData] = useState(commentData);
  const [selectedProject, setSelectedProject] = useState("All");
  const [filteredData, setFilteredData] = useState(commentData);
  const [searchQuery, setSearchQuery] = useState("");
  const [isNameSortedAscending, setIsNameSortedAscending] = useState(true);

  useEffect(() => {
    setFilteredData(
      selectedProject === "All"
        ? tableData
        : tableData.filter((item) => item.projectName === selectedProject),
    );
  }, [selectedProject, tableData]);

  useEffect(() => {
    const filteredResults = tableData.filter((item) =>
      item.name.toLowerCase().includes(searchQuery.toLowerCase()),
    );
    setFilteredData(filteredResults);
  }, [searchQuery, tableData]);

  useEffect(() => {
    setCurrentPage(1);
  }, [filteredData]);

  const totalPages = Math.ceil(filteredData.length / itemsPerPage);

  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredData
    .slice(indexOfFirstItem, indexOfLastItem)
    .sort((a, b) => {
      if (isNameSortedAscending) {
        return a.name.localeCompare(b.name);
      } else {
        return b.name.localeCompare(a.name);
      }
    });

  const paginate = (pageNumber: React.SetStateAction<number>) =>
    setCurrentPage(pageNumber);

  const renderPageNumbers = () => {
    let startPage = 1;
    let endPage = totalPages;

    if (totalPages > 5) {
      if (currentPage <= 3) {
        endPage = 5;
      } else if (currentPage >= totalPages - 2) {
        startPage = totalPages - 4;
      } else {
        startPage = currentPage - 2;
        endPage = currentPage + 2;
      }
    }

    const pages = [];
    for (let i = startPage; i <= endPage; i++) {
      pages.push(
        <button
          key={i}
          onClick={() => paginate(i)}
          className={`mx-1 rounded-md border border-gray-300 px-3 py-1 text-gray-600 ${
            currentPage === i ? "bg-gray-200" : ""
          }`}
        >
          {i}
        </button>,
      );
    }
    return pages;
  };

  const toggleNameSortOrder = () =>
    setIsNameSortedAscending(!isNameSortedAscending);

  const { user, isLoaded } = useUser();
  const user_role = user?.publicMetadata.admin;
  const router = useRouter();

  useEffect(() => {
    if (isLoaded && user_role !== "admin") {
      router.push("/home");
    }
  }, [isLoaded, user_role]);

  if (!isLoaded) {
    return <div>Loading...</div>;
  }
  if (isLoaded && user_role !== "admin") {
    return <div>UNAUTHORIZED</div>;
  }

  return (
    <>
      <Head>
        <title>Comments | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <div className="flex">
        <Sidebar />
        <div className="mx-auto w-full max-w-[1350px] p-10">
          <div className="mt-16 border-b border-black pb-4 text-2xl font-normal text-gray-800 md:text-3xl">
            COMMENTS
          </div>
          <div className="mb-3 mt-10 flex text-sm">
            <FilterByProjectName
              selectedProject={selectedProject}
              handleProjectSelect={setSelectedProject}
              tableData={tableData}
            />
            <SearchByName
              data={tableData}
              onSearch={setFilteredData}
              selectedProject={selectedProject}
            />
          </div>
          <div className="flex justify-center">
            <table className="w-full rounded-t-lg border-2">
              <thead className="bg-gray-100">
                <tr>
                  <th className="border border-gray-700 border-r-gray-100 py-3 pl-8 text-left text-sm font-medium text-gray-700">
                    <div
                      className="flex cursor-pointer items-center"
                      onClick={toggleNameSortOrder}
                    >
                      {isNameSortedAscending ? (
                        <span>
                          <AiOutlineSortAscending size={17} />
                        </span>
                      ) : (
                        <span>
                          <AiOutlineSortDescending size={17} />
                        </span>
                      )}
                      <span className="ml-1">Name</span>
                    </div>
                  </th>
                  <th className="border border-gray-700 border-r-gray-100 py-3 pl-8 text-left text-sm font-medium text-gray-700">
                    Email
                  </th>
                  <th className="border border-gray-700 border-r-gray-100 py-3 pl-8 text-left text-sm font-medium text-gray-700">
                    Comment
                  </th>
                  <th className="border border-gray-700 border-r-gray-100 py-3 pl-8 text-left text-sm font-medium text-gray-700">
                    Date
                  </th>
                  <th className="border border-gray-700 py-3 pl-8 text-left text-sm font-medium text-gray-700">
                    Project Name
                  </th>
                </tr>
              </thead>
              <tbody>
                {currentItems.map((item, index) => (
                  <tr key={index}>
                    <td className="border-2 border-r-white py-4 pl-8 text-left text-sm font-light text-gray-700">
                      {item.name}
                    </td>
                    <td className="border-2 border-r-white py-4 pl-8 text-left text-sm font-light text-gray-700">
                      {item.email}
                    </td>
                    <td className="max-w-[300px]  border-2 border-r-white py-4 pl-8 text-left text-sm font-light text-gray-700">
                      {item.comment}
                    </td>
                    <td className="border-2 border-r-white py-4 pl-8 text-left text-sm font-light text-gray-700">
                      {item.date}
                    </td>
                    <td className="border-2 py-4 pl-8 text-left text-sm font-light text-gray-700">
                      {item.projectName}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex items-center justify-between border-2 border-t-white py-3">
            <button
              onClick={() => {
                if (currentPage !== 1) {
                  paginate(currentPage - 1);
                }
              }}
              disabled={currentPage === 1}
              className={`ml-5 flex items-center rounded-md border bg-gray-50 px-3 py-1 text-gray-600 ${
                currentPage !== 1 ? "cursor-pointer hover:bg-gray-200" : ""
              }`}
            >
              <GrFormPreviousLink size={22} />
              <span className="text-sm">Previous</span>
            </button>
            <div className="flex">{renderPageNumbers()}</div>
            <button
              onClick={() => paginate(currentPage + 1)}
              disabled={indexOfLastItem >= filteredData.length}
              className={`mr-5 flex items-center rounded-md border bg-gray-50 px-3 py-1 text-gray-600 ${
                indexOfLastItem < filteredData.length
                  ? "cursor-pointer hover:bg-gray-200"
                  : ""
              }`}
            >
              <span className="text-sm">Next</span>
              <GrFormNextLink size={22} />
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Comments;
