import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Footer } from "~/components/Footer";
import { Navbar } from "~/components/Navbar";
import EditorOutput from "~/components/editor/EditorOutput";
import { api } from "~/utils/api";

const SpecificProjectDetails = () => {
  const router = useRouter();
  const { id } = router.query;
  const [projectData, setProjectData] = useState<any>(null);
  const [editorBlocks, setEditorBlocks] = useState([]);
  const [initialEditorData, setinitialEditorData] = useState();
  const getProject = api.project.getById.useQuery({ id: id as string });

  useEffect(() => {
    if (getProject.data && !projectData && getProject.data !== projectData) {
      setProjectData(getProject.data);
      const initialEditorData = JSON.parse(getProject.data.about);
      setinitialEditorData(initialEditorData);
      setEditorBlocks(initialEditorData.blocks);
    }
  }, [getProject.data, projectData]);

  return (
    <div className="mt-20 md:mt-28 ">
      <Head>
        <title> Project | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <Navbar />

      {projectData && (
        <div className="mx-auto mb-12 max-w-[1350px]">
          <EditorOutput content={initialEditorData} />
        </div>
      )}

      <Footer />
    </div>
  );
};

export default SpecificProjectDetails;
