import Head from "next/head";
import { Footer } from "~/components/Footer";
import { Navbar } from "~/components/Navbar";
import { partners } from "~/data/partners";

const Partners = () => {
  return (
    <>
      <Head>
        <title>Global Shapers Iloilo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <Navbar />
      <div
        className="mt-[65px] bg-contain pb-20 pt-20 md:mt-[100px]"
        style={{
          backgroundImage: " url('partner-bg.png')",
          backgroundSize: "100% 100%",
        }}
      >
        <div className="mx-auto flex max-w-[340px] flex-col items-center rounded-xl bg-white p-8 shadow-xl sm:max-w-[600px] md:max-w-[720px] lg:max-w-[960px]">
          <div className="mb-8 text-center text-3xl">
            In collaboration with:
          </div>
          <div className="grid grid-cols-1 gap-12 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
            {partners.map((partner, index) => (
              <div key={index} className="rounded-md">
                <img src={partner.image} className="h-32 w-60 object-contain" />
              </div>
            ))}
          </div>
          <div className="mb-6 mt-2 text-center text-3xl">Supported by:</div>
          <div className="flex items-center justify-center">
            <img
              src="city-of-iloilo.jpeg"
              className="h-36 w-56 object-contain"
            ></img>
            <img
              src="doe-iloilo.jpeg"
              className="h-36 w-56 object-contain"
            ></img>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Partners;
