import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import { Footer } from "~/components/Footer";
import { Navbar } from "~/components/Navbar";
import { impactAreasData } from "~/data/impactAreasData";

type Impact = {
  impactName: string;
  title: string;
  excerpt: string;
  image: string;
  description: string;
};

interface ImpactPageProps {
  impact: Impact;
}

const ImpactPage: React.FC<ImpactPageProps> = ({ impact }) => {
  return (
    <div>
      <Head>
        <title> Impact | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>
      <Navbar />

      <div className="mx-auto mb-12 flex max-w-[1300px] flex-col-reverse items-center md:mt-40 md:flex-row">
        <div className="w-full px-8 md:w-1/2">
          <p className="lg:text-6x mb-4 mt-6 text-center text-5xl font-semibold text-gray-700 md:mb-8 md:mt-0 md:text-left">
            {impact.title}
          </p>
          <p className="text-base font-light md:max-w-[400px] lg:max-w-[520px] lg:text-xl">
            {impact.description}
          </p>
        </div>
        <div className="mt-36 w-full px-8 md:mt-0 md:w-1/2">
          <img src={impact.image} className="h-96 w-full rounded-3xl" />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = impactAreasData.map((impact) => ({
    params: { impactName: impact.impactName },
  }));

  return { paths, fallback: false };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const { impactName } = params || {};
  const impact = impactAreasData.find((p) => p.impactName === impactName);

  return {
    props: {
      impact,
    },
  };
};

export default ImpactPage;
