import Head from "next/head";
import Link from "next/link";
import { Footer } from "~/components/Footer";
import { Navbar } from "~/components/Navbar";
import { impactAreasData } from "~/data/impactAreasData";

const Impact = () => {
  return (
    <>
      <Head>
        <title>Impact | Global Shapers Iloilo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <Navbar />

      <div className="mx-auto mt-32 max-w-[365px] flex-col items-center  px-2 sm:max-w-[405px] md:max-w-[810px] xl:max-w-[1220px]">
        <div className="text-gray text-3xl lg:text-4xl">Areas of Impact</div>
        <hr className="dark-bg-gray-800 my-4 mb-8 h-px border-0 bg-gray-800"></hr>
      </div>

      <div className="mb-12 flex items-center justify-center">
        <ul className="grid grid-cols-1 gap-6 px-2 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3">
          {impactAreasData.map((card, index) => (
            <li
              key={index}
              className="hover:scale-104 w-[350px] transform shadow transition duration-500 ease-in-out hover:-translate-y-1 sm:w-[385px]"
            >
              <div className="flex items-center">
                <div className="flex-1">
                  <img className="h-40 w-36" src={card.image} />
                </div>
                <div className="mx-2 my-2 flex-1">
                  <div className="w-52 text-lg font-semibold tracking-tight text-gray-900">
                    {card.title}
                  </div>

                  <div className=" mt-1 text-sm font-light text-gray-900">
                    {card.excerpt}
                  </div>
                </div>
              </div>
            </li>
          ))}
        </ul>
      </div>
      <Footer />
    </>
  );
};

export default Impact;
