/* eslint-disable @typescript-eslint/require-await */
import { type GetServerSideProps } from 'next';
import { getAuth } from '@clerk/nextjs/server';
import Head from 'next/head';
import { Navbar } from '~/components/Navbar';

interface HomeProps {
  userId: string;
 }
 
 export const getServerSideProps: GetServerSideProps = async (context) => {
  const { req } = context;
  const { userId } = getAuth(req);
 
  // Pass userId to the page via props
  return { props: { userId } };
 };
 
 export default function Home({ userId }: HomeProps) {
  console.log(userId);
 
  return (
    <>
      <Head>
        <title>Global Shapers Iloilo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.jpeg" />
      </Head>
 
      <Navbar />

      <div> logged in</div>
      {!userId &&(
        <>
        <Head>
        <title>Global Shapers Iloilo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.jpeg" />
      </Head>
 
      <Navbar />

      <div> not logged in</div>
        
        </>
      )

      }
    </>
  );
 }
