import Head from "next/head";
import { Navbar } from "~/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Global Shapers Iloilo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.jpeg" />
      </Head>

      <Navbar />
    </>
  );
}
