import Head from "next/head";
import { useState, useEffect, MutableRefObject, useRef } from "react";
import { Editor } from "@tinymce/tinymce-react";
import { Sidebar } from "~/components/Sidebar";
import Select from "react-select";
import { api } from "~/utils/api";
import { categoriesOption } from "~/data/categories";

function EditProjects() {
  const getProject = api.project.getById.useMutation();
  console.log("Project data", getProject);

  const editProject = api.project.edit.useMutation({
    onError: (error) => {
      console.log("Error editing project:", error);
    },
  });

  const [projectData, setProjectData] = useState({
    title: "",
    description: "",
    image: "",
    hub: "",
    category: "",
    type: "",
    beneficiaries: "",
    about: "",
  });

  const editorRef: MutableRefObject<any> = useRef(null);

  useEffect(() => {
    if (getProject.data) {
      setProjectData(getProject.data);
    }
  }, [getProject.data]);

  const typeOptions = [
    { label: "Activity", value: "Activity" },
    { label: "Project", value: "Project" },
  ];

  const handleChange = (e: { target: { name: any; value: any } }) => {
    const { name, value } = e.target;
    setProjectData({ ...projectData, [name]: value });
  };

  const handleCategoryChange = (selectedOption: { value: any }) => {
    setProjectData({ ...projectData, category: selectedOption.value });
  };

  const handleTypeChange = (selectedOption: { value: any }) => {
    setProjectData({ ...projectData, type: selectedOption.value });
  };

  const handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();

    editProject.mutate({
      ...projectData,
      id: "",
      published: false,
    });
  };

  return (
    <div>
      <Head>
        <title>Edit Project | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <div className="flex">
        <Sidebar />

        <div className="flex-1 p-8">
          <div className="mt-10 text-4xl font-normal text-gray-800">
            Edit Project
          </div>

          <hr className="dark-bg-gray-800 my-4 h-px border-0 bg-gray-800"></hr>

          <form onSubmit={handleSubmit}>
            <div className="mb-4">
              <label htmlFor="title" className="font-medium text-gray-700">
                Project Title
              </label>
              <input
                type="text"
                id="title"
                name="title"
                value={projectData.title}
                onChange={handleChange}
                className="mt-1 w-full rounded-md border p-2 shadow-sm"
                required
              />
            </div>

            <div className="mb-4">
              <label
                htmlFor="description"
                className="font-medium text-gray-700"
              >
                Project Description
              </label>
              <input
                type="text"
                id="description"
                name="description"
                value={projectData.description}
                onChange={handleChange}
                className="mt-1 w-full rounded-md border p-2 shadow-sm"
                required
              />
            </div>

            <div className="mb-4">
              <label htmlFor="image" className="font-medium text-gray-700">
                Featured Image
              </label>
            </div>

            <div className="mb-4">
              <label
                htmlFor="beneficiaries"
                className="font-medium text-gray-700"
              >
                Beneficiaries
              </label>
              <input
                type="text"
                id="beneficiaries"
                name="beneficiaries"
                value={projectData.beneficiaries}
                onChange={handleChange}
                className="mt-1 w-full rounded-md border p-2 shadow-sm"
                required
              />
            </div>

            <div className="mb-4">
              <label htmlFor="hub" className="block font-medium text-gray-700">
                Hub
              </label>
              <input
                type="text"
                id="hub"
                name="hub"
                value={projectData.hub}
                onChange={handleChange}
                className="mt-1 w-full rounded-md border p-2 shadow-sm"
                required
              />
            </div>

            <div className="mb-4">
              <label htmlFor="category" className="font-medium text-gray-700">
                Category
              </label>
              <Select
                options={categoriesOption}
                value={categoriesOption.find(
                  (option) => option.value === projectData.category,
                )}
                onChange={(selectedOption: { value: any } | null) =>
                  handleCategoryChange(selectedOption?.value)
                }
                className="z-20"
              />
            </div>

            <div className="mb-4">
              <label htmlFor="type" className="font-medium text-gray-700">
                Type
              </label>
              <Select
                options={typeOptions}
                value={typeOptions.find(
                  (option) => option.value === projectData.type,
                )}
                onChange={(selectedOption: { value: any } | null) =>
                  handleTypeChange(selectedOption?.value)
                }
                className="z-10"
              />
            </div>

            <div className="mb-4">
              <label htmlFor="about" className="font-medium text-gray-700">
                About
              </label>
            </div>

            <Editor
              apiKey={process.env.NEXT_PUBLIC_TINYMCE_API_KEY}
              onInit={(evt, editor) => {
                if (editorRef.current === null) {
                  editorRef.current = editor;
                }
              }}
              initialValue={projectData.about}
              init={{
                width: "100%",
                height: 600,
                plugins: [
                  "advlist",
                  "link",
                  "image",
                  "lists",
                  "preview",
                  "pagebreak",
                  "wordcount",
                  "fullscreen",
                  "insertdatetime",
                  "media",
                  "table",
                  "emoticons",
                  "code",
                ],
                toolbar:
                  "undo redo |fontfamily fontsize | bold italic underline | alignleft aligncenter alignright alignjustify |" +
                  "bullist numlist outdent indent | link image | preview media fullscreen | " +
                  "forecolor backcolor emoticons",

                menubar: "file edit insert view  format table tools",
                content_style:
                  "body{font-family:Helvetica,Arial,sans-serif; font-size:16px}",
                // images_upload_url: "http://localhost:8000/server.php",
              }}
            />

            <button
              type="submit"
              className="mt-4 rounded-lg bg-blue-800 px-4 py-2 font-medium text-white"
            >
              PUBLISH
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

export default EditProjects;
