import Head from "next/head";
import { useState, useEffect } from "react";
import Link from "next/link";
import ProjectCard from "./components/ProjectCard";
import Header from "./components/Header";
import { Sidebar } from "~/components/Sidebar";
import { api } from "~/utils/api";

const AdminProjectPage = () => {
  const [projectData, setProjectData] = useState<any>([]);

  const getProjects = api.project.getAll.useQuery();

  useEffect(() => {
    if (getProjects.data) {
      setProjectData(getProjects.data);
    }
  }, [getProjects.data]);

  const deleteProject = api.project.delete.useMutation();

  const handleDelete = () => {
    try {
      deleteProject.mutate({ id: projectData.id });
    } catch (error) {
      console.error("Error deleting project:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Projects | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>
      <div className="border-4px flex">
        <Sidebar />
        <div className="flex-1 bg-gray-100 p-10">
          <Header> PROJECTS</Header>
          <div className="  mt-12 items-center justify-between overflow-hidden md:flex">
            <div className="py-2 md:ml-2 md:flex md:px-2">
              <Link href={`/admin/projects/create`}>
                <button className="w-72 rounded-lg bg-blue-800 px-16 py-2 text-lg font-light text-white hover:bg-blue-900">
                  Create Project
                </button>
              </Link>
            </div>
          </div>

          <div
            className="
          mb-12
           mt-4 
           flex 
           items-center 
           justify-center
          "
          >
            <div
              className="
          mt-4
          grid
          grid-cols-1
          gap-4
          sm:grid-cols-2
          md:grid-cols-2
          lg:grid-cols-2
          xl:grid-cols-4
            "
            >
              {projectData.map((card: any, index: any) => (
                <div className=" hover:bg-neutral-400/10">
                  <ProjectCard
                    key={index}
                    projectData={card}
                    onDelete={() => handleDelete()}
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default AdminProjectPage;
