import Head from "next/head";
import Header from "../header";
import { RiSearchLine } from "react-icons/ri";
import { useState, SetStateAction } from "react";
import Link from "next/link";
import FilterByCategory from "~/components/filter/Categories";
import { projectData } from "~/data/projectData";
import ProjectCard from "./components/ProjectCard";

const AdminProjectPage = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("Categories");
  const [isCategoryListOpen, setIsCategoryListOpen] = useState(false);

  const toggleCategoryList = () => {
    setIsCategoryListOpen(!isCategoryListOpen);
  };

  const handleCategorySelect = (category: SetStateAction<string>) => {
    setSelectedCategory(category);
    setIsCategoryListOpen(false);
  };

  return (
    <>
      <div className="border-4px">
        <Head>
          <title>Global Shapers Iloilo</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/gsi-logo.jpeg" />
        </Head>
        <div className="flex-1 bg-gray-100 p-10">
          <Header> PROJECTS</Header>
          <div className="  mt-12 items-center justify-between overflow-hidden md:flex">
            <div className="relative z-10 flex ">
              <div className="relative mr-2 flex items-center md:py-2">
                {" "}
                <FilterByCategory
                  selectedCategory={selectedCategory}
                  isCategoryListOpen={isCategoryListOpen}
                  toggleCategoryList={toggleCategoryList}
                  handleCategorySelect={handleCategorySelect}
                />
              </div>
            </div>

            <div className="relative mr-2 flex items-center md:flex py-2 w-full">
                  <input
                    type="text"
                    placeholder="Search"
                    className="rounded-md border border-gray-600 py-2 pl-8 pr-4 md:ml-1"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                  <RiSearchLine
                    className=" absolute left-4 top-5 text-gray-500 sm:left-3"
                    size={20}
                  />
              </div>

            <div className="py-2 md:ml-2 md:flex md:px-2">
              <Link href={`/admin/projects/create`}>
                <button className="w-72 rounded-lg bg-blue-800 px-16 py-2 text-lg font-light text-white hover:bg-blue-900">
                  Create Project
                </button>
              </Link>
            </div>
          </div>

          <div
            className="
          mb-12
           mt-4 
           flex 
           items-center 
           justify-center
          "
          >
            <div
              className="
          mt-4
          grid
          grid-cols-1
          gap-4
          sm:grid-cols-2
          md:grid-cols-2
          lg:grid-cols-3
          xl:grid-cols-3
          2xl:grid-cols-3"
            >
              {projectData
                .filter(
                  (card) =>
                    selectedCategory === "Categories" ||
                    card.category === selectedCategory,
                )
                .filter((card) =>
                  card.projectTitle
                    .toLowerCase()
                    .includes(searchQuery.toLowerCase()),
                )
                .map((card, index) => (
                  <div className=" hover:bg-neutral-400/10">
                    <ProjectCard projectData={card} index={index} />
                  </div>
                ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default AdminProjectPage;
