import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Footer } from "~/components/Footer";
import { Navbar } from "~/components/Navbar";
import { projectData } from "~/data/projectData";

const Tech4all = () => {
  const [showBackgroundImage, setShowBackgroundImage] = useState(false);

  useEffect(() => {
    const handleResize = () => {
      setShowBackgroundImage(window.innerWidth >= 768);
    };
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const project = projectData.length > 0 ? projectData[0] : null;

  return (
    <>
      <Head>
        <title>Global Shapers Iloilo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <Navbar />

      {project && (
        <>
          <div
            className={`${
              showBackgroundImage ? "md:-h-[1000px]" : ""
            } mt-[65px] bg-contain md:mt-[100px] lg:h-[644px]`}
            style={{
              backgroundImage: showBackgroundImage
                ? "url('/tech4all-bg.png')"
                : "url('/tech4all-bg2.png')",
              backgroundSize: "100% 100%",
            }}
          >
            <div className="mx-auto lg:max-w-[1200px] xl:max-w-[1230px] ">
              <div className="flex flex-col-reverse items-center sm:pt-16 lg:flex-row lg:pt-28 ">
                <div className="w-full flex-col items-center justify-center lg:w-1/2">
                  <p
                    className={`mb-2 mt-2 px-4 text-xl font-medium text-[${project.themeColor}] sm:mb-4 sm:mt-8 sm:px-6 sm:text-2xl lg:mt-4 lg:text-3xl xl:px-0 xl:text-4xl`}
                  >
                    {project.projectTitle}
                  </p>
                  <p className="mb-2 px-4 text-xs font-light text-gray-800 sm:max-w-[700px] sm:px-6 sm:text-base md:max-w-[750px] lg:max-w-[530px] xl:px-0 xl:text-lg">
                    {project.projectDescription}
                  </p>
                  <p className="mb-8 px-4 text-xs font-light text-gray-800 sm:px-6 sm:text-base md:mb-44 md:max-w-[530px] lg:mb-0 lg:text-lg xl:px-0">
                    Connect with us:
                    <Link
                      href={project.projectLink}
                      className={`ml-2 font-medium text-[${project.themeColor}] underline`}
                    >
                      {project.projectLinkTitle}
                    </Link>
                  </p>
                </div>

                <div className="mt-2 w-full rounded-md px-4 sm:px-6 lg:w-1/2 lg:max-w-[650px] lg:pr-6 xl:ml-12 xl:px-0">
                  <img
                    src={project.projectImage}
                    className="min-h-[260px] min-w-[200px] rounded-md sm:min-h-[350px]"
                    alt="techforall"
                  ></img>
                </div>
              </div>
            </div>
          </div>

          <div
            className={`mt-10 flex items-center justify-center text-2xl font-medium text-[${project.themeColor}]  sm:text-3xl lg:mt-24 xl:text-4xl`}
          >
            Project Objectives
          </div>

          <div className="mx-auto mb-1 mt-1 px-4 text-center text-xs font-light sm:text-base md:mt-3 md:max-w-[720px] lg:mb-10 lg:max-w-[950px] xl:text-lg">
            {project.objectiveDescription}
          </div>

          <div className="">
            <img
              src={project.objectives}
              className="mx-auto mb-10 h-[460px] w-[1250px]"
              alt="Project Objectives"
            ></img>
          </div>

          <div className="mx-auto mb-10 grid max-w-[1360px] grid-cols-1 items-center justify-center md:mb-16 lg:grid-cols-2">
            <div className="flex-col">
              <div
                className={`mb-1 text-center text-2xl font-medium text-[${project.themeColor}]  md:text-3xl`}
              >
                {project.project1}
              </div>
              <div className="mb-3 text-center text-sm font-light md:text-base">
                {project.subtitle1}
              </div>
              <img
                src={project.imgSrc1}
                className={`mx-auto w-[680px] border-[${project.themeColor}] md:h-[560px] lg:border-r-4 lg:pr-10`}
                alt="Robotopia"
              ></img>
            </div>

            <div className="flex-col lg:pl-8">
              <div
                className={`mb-1 mt-12 text-center text-2xl font-medium text-[${project.themeColor}]  md:mt-16 md:text-3xl lg:mt-0`}
              >
                {project.project2}
              </div>
              <div className="mb-3 text-center text-sm font-light md:text-base">
                {project.subtitle2}
              </div>

              <img
                src={project.imgSrc2}
                className="mx-auto h-[560px] w-[680px]"
                alt="Gameon"
              ></img>
            </div>
          </div>
        </>
      )}

      <Footer />
    </>
  );
};

export default Tech4all;
