import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Sidebar } from "~/components/Sidebar";
import { api } from "~/utils/api";
import Head from "next/head";
import EditorOutput from "~/components/editor/EditorOutput";
import { useUser } from "@clerk/nextjs";
import Loading from "~/components/Loading";
import Unauthorized from "~/components/Unauthorized";

const ProjectDetailsPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [projectData, setProjectData] = useState<any>(null);
  const [editorBlocks, setEditorBlocks] = useState([]);
  const [initialEditorData, setinitialEditorData] = useState();
  const getProject = api.project.getById.useQuery({ id: id as string });

  useEffect(() => {
    if (getProject.data && !projectData && getProject.data !== projectData) {
      setProjectData(getProject.data);
      const initialEditorData = JSON.parse(getProject.data.about);
      setinitialEditorData(initialEditorData);
      setEditorBlocks(initialEditorData.blocks);
    }
  }, [getProject.data, projectData]);

  const { user, isLoaded } = useUser();
  const user_role = user?.publicMetadata.admin;

  useEffect(() => {}, [isLoaded, user_role]);
  if (!isLoaded) {
    return <Loading/>
  }
  if (user_role !== "admin") {
    return <Unauthorized />;
  }

  return (
    <div className="flex">
      <Head>
        <title> Project | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <Sidebar />

      {projectData && (
        <div className="mx-auto mb-12 mt-8 max-w-[1200px]">
          <EditorOutput content={initialEditorData} />
        </div>
      )}
    </div>
  );
};

export default ProjectDetailsPage;
