import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import React, { useEffect } from "react";
import LoadingSpinner from "~/components/LoadingSpinner";
import { Sidebar } from "~/components/Sidebar";
import Unauthorized from "~/components/Unauthorized";

export const Admin = () => {
  const { user, isLoaded } = useUser();
  const user_role = user?.publicMetadata.admin;

  useEffect(() => {}, [isLoaded, user_role]);
  if (!isLoaded) {
    return <LoadingSpinner />;
  }
  if (user_role !== "admin") {
    return <Unauthorized />;
  }

  return (
    <>
      <Head>
        <title>Dashboard | Global shapers</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/gsi-logo.png" />
      </Head>

      <div className="flex">
        <Sidebar />
        <div className="mx-auto mt-72 text-5xl"> Dashboard </div>
      </div>
    </>
  );
};

export default Admin;
